### ISSUE TITLE
open posts in new tab

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/blog#9]
when you click a post, it should open in a new tab

**Comment by Elaa257** [comment]
Hi, do you need help on solving this issue? If so, I would like to contribute :)

**Comment by raspberri05** [comment]
Hi! feel free to work on the issue, and I can review the PR once you've opened it. Please let me know if you need any help

**Comment by Elaa257** [comment]
@raspberri05 Just started working on the issue, is there a reason why the index-file is .md and not .html ?

**Comment by raspberri05** [comment]
The site was made with jekyll, which essentially uses markdown files with html templates. I'd recommend taking a look at the jekyll docs to familiarize yourself with the file structure. Please me know if you need any additional explanations or clarifications. 

https://jekyllrb.com/docs/step-by-step/01-setup/

**Comment by Elaa257** [comment]
@raspberri05 thank you, I will have a look :)
